### ISSUE TITLE
when enabled development signing build fails

### ISSUE THREAD

**Issue by liam2003** [insleep/spark-web-browser#30]

**Comment by liam2003** [comment]
when you download the source code and try to enable development signing and then try to build the build fails with command code sign failed

**Comment by liam2003** [comment]
Command CodeSign failed with a nonzero exit code

**Comment by insleep** [comment]
This error is not related to Spark, it is a problem on the client computer. In order to sign the project, you must have an active Apple developer license.

If you have an active license, please follow the instructions [here](https://stackoverflow.com/questions/52421999/xcode-10-command-codesign-failed-with-a-nonzero-exit-code) to fix this.

Additionally, you do not need to sign Spark to compile it. If none of the solutions work in the link provided above, try compiling without signing.
