### ISSUE TITLE
Resizing browser window

### ISSUE THREAD

**Issue by gitguys** [insleep/spark-web-browser#31]
I'm unable to shrink the browser window vertically and especially horizontally as small as I need to.

Can you remove that restriction so the window can be sized much smaller like one can do with the Safari browser, etc.?

**Comment by insleep** [comment]
Thanks for your feedback -- this has been fixed in the latest nightly channel build (3.4.2n.331). If you're on the nightly channel, you can update via Spark > Check for Updates. Otherwise, you can download it [directly](https://spark.insleep.tech/dev/Spark-3.4.2n.331.zip).

I'm not sure when it'll make it to the stable channel but it will probably be pretty soon. The current nightly build has a few small issues but once those are ironed out I'll release a new stable channel version.
